### PR TITLE
Major refactoring of our codebase

### PR DESCRIPTION
**Pull request by awesometic**
The changes.
- Change code structure. Now Monitor class manages all of the background workers.
- Renaming **commit** and **observer** to **record** and **hooker**.
- Implementing multi threading for debugging **MediaHooker** and **RouteTracker**.
- Clean code.
- And more I might forget?

Sorry for making only one commit with these huge changes.
Please review them.

screen shot 2018-04-04 at 11 02 12 pm

### CODE REVIEW

**Comment by awesometic** [comment]
This PR includes the 3 commits already rebased :open_mouth:

**Comment by xiane** [comment]
Please follow the commend line instructions shown on conflict message.

**Comment by awesometic** [comment]
Okay I'll close this PR and pull the latest changes from your master branch, and I'll work on them a little bit to make it works as well.
After then I will open a new PR again.

Please keep this PR opened until I close. I might forget :smile: 
I will do by tomorrow.

Edit: If you find anything weird or to be improved, please let me know.

**Comment by awesometic** [comment]
Okay, fortunately I hadn't needed to delete and make PR again.
And I've found just one bug -> END button doesn't work well due to the threads on Tracker and Hooker. DispatchWorkItem.cancel() doesn't do as I expected, and maybe DispatchQueue could be the culprit I think. I'll keep investigating that.

**Comment by xiane** [comment]
The PR has also thread functionality like GCD. we should know it.

**Pull request merged**
